---
- name: Pull and run docker container
  hosts: all
  gather_facts: False
  tasks:
    - name: Download image and run container
      docker_container:
        name: reddit
        image: "mkosterin/otus-reddit:1.0"
        ports:
          - "9292:9292"

