FROM alpine:3.7
RUN apk add --no-cache ruby ruby-dev ruby-bundler build-base \
    && gem install  bundler --no-ri --no-rdoc

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY Gemfile* $APP_HOME/
RUN bundle install
COPY . $APP_HOME

CMD ["puma"]

